# Generated by Django 4.2.7 on 2025-12-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='뉴스 소스의 이름입니다. 예: 경향신문', max_length=100, unique=True, verbose_name='소스 이름')),
                ('url', models.URLField(help_text='RSS 피드 URL 또는 API 엔드포인트 주소', max_length=500, verbose_name='URL')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('api', 'API'), ('scraping', '웹 스크래핑')], default='rss', help_text='데이터 수집 방식', max_length=20, verbose_name='소스 타입')),
                ('is_active', models.BooleanField(default=True, help_text='이 소스에서 데이터를 수집할지 여부', verbose_name='활성화')),
                ('collection_interval', models.IntegerField(default=60, help_text='데이터를 수집하는 주기 (분 단위)', verbose_name='수집 주기(분)')),
                ('last_collected_at', models.DateTimeField(blank=True, help_text='이 소스에서 마지막으로 데이터를 수집한 시간', null=True, verbose_name='마지막 수집 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '뉴스 소스',
                'verbose_name_plural': '뉴스 소스',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', help_text='작업 상태 (pending: 대기 중, running: 실행 중, completed: 완료, failed: 실패)', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='작업이 시작된 시간', verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, help_text='작업이 완료된 시간', null=True, verbose_name='완료 시간')),
                ('items_collected', models.IntegerField(default=0, help_text='이 작업에서 수집한 데이터 개수', verbose_name='수집 개수')),
                ('error_message', models.TextField(blank=True, help_text='작업이 실패한 경우 에러 메시지', null=True, verbose_name='에러 메시지')),
                ('source', models.ForeignKey(blank=True, help_text='이 작업이 실행된 뉴스 소스', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_jobs', to='data_collector.newssource', verbose_name='뉴스 소스')),
            ],
            options={
                'verbose_name': '데이터 수집 작업',
                'verbose_name_plural': '데이터 수집 작업',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='뉴스 기사의 제목', max_length=500, verbose_name='제목')),
                ('url', models.URLField(db_index=True, help_text='뉴스 기사의 원본 URL (중복 방지용)', max_length=1000, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='뉴스 기사의 요약 또는 설명', null=True, verbose_name='설명')),
                ('content', models.TextField(blank=True, help_text='뉴스 기사의 전체 본문 내용', null=True, verbose_name='내용')),
                ('author', models.CharField(blank=True, help_text='기사를 작성한 기자 또는 작성자', max_length=200, null=True, verbose_name='작성자')),
                ('category', models.CharField(blank=True, db_index=True, help_text='기사의 카테고리 (예: 정치, 경제, 사회 등)', max_length=100, null=True, verbose_name='카테고리')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='기사가 발행된 시간 (RSS 피드에서 가져온 시간)', null=True, verbose_name='발행 시간')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='이 기사를 수집한 시간', verbose_name='수집 시간')),
                ('is_processed', models.BooleanField(default=False, help_text='이 기사가 분석 처리되었는지 여부', verbose_name='처리 완료')),
                ('source', models.ForeignKey(help_text='이 기사를 수집한 뉴스 소스', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='data_collector.newssource', verbose_name='뉴스 소스')),
            ],
            options={
                'verbose_name': '뉴스 기사',
                'verbose_name_plural': '뉴스 기사',
                'ordering': ['-published_at', '-collected_at'],
                'indexes': [models.Index(fields=['-published_at', '-collected_at'], name='data_collec_publish_6a79fe_idx'), models.Index(fields=['source', '-published_at'], name='data_collec_source__f6391f_idx')],
            },
        ),
    ]
