# Generated by Django 4.2.7 on 2025-12-03 08:49

from django.db import migrations, models


def migrate_name_to_publisher_category(apps, schema_editor):
    """
    기존 name 필드 값을 publisher와 category로 분리
    예: "경향신문 - 정치" -> publisher="경향신문", category="정치"
    """
    NewsSource = apps.get_model('data_collector', 'NewsSource')
    
    for source in NewsSource.objects.all():
        if hasattr(source, 'name') and source.name:
            # "신문사 - 카테고리" 형식으로 분리
            if ' - ' in source.name:
                parts = source.name.split(' - ', 1)
                source.publisher = parts[0].strip()
                source.category = parts[1].strip() if len(parts) > 1 else None
            else:
                # " - "가 없으면 전체를 publisher로, category는 None
                source.publisher = source.name.strip()
                source.category = None
            source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={'ordering': ['publisher', 'category', '-created_at'], 'verbose_name': '뉴스 소스', 'verbose_name_plural': '뉴스 소스'},
        ),
        migrations.AddField(
            model_name='newssource',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='뉴스 카테고리 (예: 정치, 경제, 사회 등)', max_length=100, null=True, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='publisher',
            field=models.CharField(db_index=True, default='Unknown', help_text='뉴스 소스의 신문사 이름입니다. 예: 경향신문', max_length=100, verbose_name='신문사'),
            preserve_default=False,
        ),
        # 데이터 마이그레이션: name 값을 publisher와 category로 분리
        migrations.RunPython(migrate_name_to_publisher_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(help_text='RSS 피드 URL 또는 API 엔드포인트 주소', max_length=500, unique=True, verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='newssource',
            unique_together={('publisher', 'category', 'url')},
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='name',
        ),
    ]
