# Generated by Django 4.2.7 on 2025-12-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_alter_newssource_options_newssource_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='publisher',
            field=models.CharField(db_index=True, default='Unknown', help_text='뉴스 소스의 신문사 이름입니다. 예: 경향신문', max_length=100, verbose_name='신문사'),
        ),
        migrations.CreateModel(
            name='CollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='수집 세션이 시작된 시간', verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, help_text='수집 세션이 완료된 시간', null=True, verbose_name='완료 시간')),
                ('status', models.CharField(choices=[('running', '실행 중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소됨')], default='running', help_text='세션 상태', max_length=20, verbose_name='상태')),
                ('total_sources', models.IntegerField(default=0, help_text='처리 대상인 총 NewsSource 개수', verbose_name='총 소스 수')),
                ('successful_sources', models.IntegerField(default=0, help_text='성공적으로 수집 완료된 소스 개수', verbose_name='성공한 소스 수')),
                ('failed_sources', models.IntegerField(default=0, help_text='수집에 실패한 소스 개수', verbose_name='실패한 소스 수')),
                ('total_articles_collected', models.IntegerField(default=0, help_text='이 세션에서 수집된 총 NewsArticle 개수', verbose_name='총 수집 기사 수')),
                ('total_articles_skipped', models.IntegerField(default=0, help_text='중복 등으로 건너뛴 기사 개수', verbose_name='건너뛴 기사 수')),
                ('total_articles_error', models.IntegerField(default=0, help_text='저장 중 오류가 발생한 기사 개수', verbose_name='오류 기사 수')),
                ('duration_seconds', models.FloatField(blank=True, help_text='세션 시작부터 완료까지 소요된 시간', null=True, verbose_name='소요 시간 (초)')),
                ('json_report_path', models.CharField(blank=True, help_text='생성된 JSON 리포트 파일 경로', max_length=500, null=True, verbose_name='JSON 리포트 경로')),
                ('markdown_report_path', models.CharField(blank=True, help_text='생성된 마크다운 리포트 파일 경로', max_length=500, null=True, verbose_name='마크다운 리포트 경로')),
                ('notes', models.TextField(blank=True, help_text='세션에 대한 추가 메모', null=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '수집 세션',
                'verbose_name_plural': '수집 세션',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='data_collec_started_fbc261_idx'), models.Index(fields=['status', '-started_at'], name='data_collec_status_30864c_idx')],
            },
        ),
    ]
