# Generated by Django 4.2.7 on 2025-12-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0003_alter_newssource_publisher_collectionsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='content',
        ),
    ]
