# Generated by Django 4.2.7 on 2025-12-09 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0004_remove_newsarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('reddit', 'Reddit'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('facebook', 'Facebook')], db_index=True, help_text='소셜 미디어 플랫폼 타입', max_length=20, verbose_name='플랫폼')),
                ('identifier', models.CharField(db_index=True, help_text='플랫폼별 식별자 (Reddit: subreddit 이름, Instagram: 사용자명/해시태그)', max_length=200, verbose_name='식별자')),
                ('display_name', models.CharField(help_text='소스의 표시용 이름 (예: r/technology, @username)', max_length=200, verbose_name='표시 이름')),
                ('url', models.URLField(help_text='RSS 피드 URL 또는 API 엔드포인트 주소', max_length=500, verbose_name='URL')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('api', 'API'), ('scraping', '웹 스크래핑')], default='rss', help_text='데이터 수집 방식', max_length=20, verbose_name='소스 타입')),
                ('category', models.CharField(blank=True, db_index=True, help_text='소스의 카테고리 또는 태그', max_length=100, null=True, verbose_name='카테고리')),
                ('is_active', models.BooleanField(default=True, help_text='이 소스에서 데이터를 수집할지 여부', verbose_name='활성화')),
                ('collection_interval', models.IntegerField(default=60, help_text='데이터를 수집하는 주기 (분 단위)', verbose_name='수집 주기(분)')),
                ('last_collected_at', models.DateTimeField(blank=True, help_text='이 소스에서 마지막으로 데이터를 수집한 시간', null=True, verbose_name='마지막 수집 시간')),
                ('api_credentials', models.JSONField(blank=True, help_text='API 인증에 필요한 정보 (JSON 형태)', null=True, verbose_name='API 인증 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '소셜 미디어 소스',
                'verbose_name_plural': '소셜 미디어 소스',
                'ordering': ['platform', 'identifier', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='socialmediapost',
            options={'ordering': ['-published_at', '-collected_at'], 'verbose_name': '소셜 미디어 게시물', 'verbose_name_plural': '소셜 미디어 게시물'},
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='author',
            field=models.CharField(blank=True, db_index=True, help_text='게시물을 작성한 사용자명', max_length=200, null=True, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='이 게시물을 수집한 시간', verbose_name='수집 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='comments_count',
            field=models.IntegerField(default=0, help_text='댓글 개수', verbose_name='댓글 수'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='content',
            field=models.TextField(blank=True, help_text='게시물의 본문 내용', null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0, help_text='Reddit 다운보트 수', null=True, verbose_name='다운보트'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='hashtags',
            field=models.JSONField(blank=True, help_text='게시물에 포함된 해시태그 목록 (JSON 배열)', null=True, verbose_name='해시태그'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='이 게시물이 분석 처리되었는지 여부', verbose_name='처리 완료'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='likes_count',
            field=models.IntegerField(default=0, help_text='좋아요, 업보트 등의 수 (플랫폼별로 의미가 다름)', verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='location',
            field=models.CharField(blank=True, help_text='게시물의 위치 정보', max_length=200, null=True, verbose_name='위치'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='media_type',
            field=models.CharField(blank=True, help_text='Instagram 미디어 타입 (IMAGE, VIDEO, CAROUSEL_ALBUM 등)', max_length=20, null=True, verbose_name='미디어 타입'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='media_url',
            field=models.URLField(blank=True, help_text='Instagram 미디어(이미지/비디오) URL', max_length=1000, null=True, verbose_name='미디어 URL'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='platform_post_id',
            field=models.CharField(db_index=True, default='', help_text='플랫폼에서 제공하는 게시물의 고유 ID', max_length=300, verbose_name='플랫폼 게시물 ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='게시물이 게시된 시간', null=True, verbose_name='게시 시간'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='플랫폼에서 받은 원본 데이터 (JSON 형태)', null=True, verbose_name='원본 데이터'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='score',
            field=models.IntegerField(blank=True, default=0, help_text='Reddit 스코어 (업보트 - 다운보트)', null=True, verbose_name='스코어'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='shares_count',
            field=models.IntegerField(default=0, help_text='공유, 리트윗 등의 수', verbose_name='공유 수'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='subreddit',
            field=models.CharField(blank=True, db_index=True, help_text='Reddit 서브레딧 이름', max_length=100, null=True, verbose_name='서브레딧'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='썸네일 이미지 URL', max_length=1000, null=True, verbose_name='썸네일 URL'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='title',
            field=models.CharField(blank=True, help_text='게시물의 제목', max_length=500, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, help_text='Reddit 업보트 수', null=True, verbose_name='업보트'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='url',
            field=models.URLField(db_index=True, default='', help_text='게시물의 원본 URL (중복 방지용)', max_length=1000, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, help_text='게시물 조회수 (플랫폼별로 제공 여부가 다름)', null=True, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='source',
            field=models.ForeignKey(blank=True, default=None, help_text='이 게시물을 수집한 소셜 미디어 소스', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data_collector.socialmediasource', verbose_name='소셜 미디어 소스'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['-published_at', '-collected_at'], name='data_collec_publish_e2cd56_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['source', '-published_at'], name='data_collec_source__a93b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['platform_post_id'], name='data_collec_platfor_748821_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['author', '-published_at'], name='data_collec_author_f835d2_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['subreddit', '-published_at'], name='data_collec_subredd_9fe938_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasource',
            index=models.Index(fields=['platform', 'is_active'], name='data_collec_platfor_1385f6_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasource',
            index=models.Index(fields=['-last_collected_at'], name='data_collec_last_co_6bfb2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediasource',
            unique_together={('platform', 'identifier', 'url')},
        ),
    ]
