# Generated by Django 4.2.7 on 2025-12-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0005_socialmediasource_alter_socialmediapost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='gall_name',
            field=models.CharField(blank=True, db_index=True, help_text='DC Inside 갤러리 이름 (예: dcbest, programming)', max_length=100, null=True, verbose_name='갤러리 이름'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='images',
            field=models.JSONField(blank=True, help_text='게시글에 포함된 이미지 URL 목록 (JSON 배열)', null=True, verbose_name='이미지 URL 목록'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='ip',
            field=models.CharField(blank=True, help_text='작성자 IP 주소 (일부만 표시)', max_length=50, null=True, verbose_name='IP 주소'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='post_num',
            field=models.CharField(blank=True, db_index=True, help_text='DC Inside 게시글 번호', max_length=50, null=True, verbose_name='글 번호'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform_post_id',
            field=models.CharField(blank=True, db_index=True, help_text='플랫폼에서 제공하는 게시물의 고유 ID', max_length=300, null=True, verbose_name='플랫폼 게시물 ID'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='source',
            field=models.ForeignKey(blank=True, help_text='이 게시물을 수집한 소셜 미디어 소스', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data_collector.socialmediasource', verbose_name='소셜 미디어 소스'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='url',
            field=models.URLField(blank=True, db_index=True, help_text='게시물의 원본 URL (중복 방지용)', max_length=1000, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasource',
            name='platform',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('dcinside', 'DC Inside'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('facebook', 'Facebook')], db_index=True, help_text='소셜 미디어 플랫폼 타입', max_length=20, verbose_name='플랫폼'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['gall_name', '-published_at'], name='data_collec_gall_na_5481cd_idx'),
        ),
    ]
