# Generated by Django 4.2.7 on 2025-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0006_socialmediapost_gall_name_socialmediapost_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='media_url',
        ),
        migrations.AlterField(
            model_name='socialmediasource',
            name='display_name',
            field=models.CharField(help_text='소스의 표시용 이름 (예: r/technology, 실시간 베스트 갤러리)', max_length=200, verbose_name='표시 이름'),
        ),
        migrations.AlterField(
            model_name='socialmediasource',
            name='identifier',
            field=models.CharField(db_index=True, help_text='플랫폼별 식별자 (Reddit: subreddit 이름, dcinside: 갤러리이름)', max_length=200, verbose_name='식별자'),
        ),
        migrations.AlterField(
            model_name='socialmediasource',
            name='platform',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('dcinside', 'DC Inside')], db_index=True, help_text='소셜 미디어 플랫폼 타입', max_length=20, verbose_name='플랫폼'),
        ),
    ]
