# Generated by Django 4.2.7 on 2025-12-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_collector', '0007_remove_socialmediapost_hashtags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollectionjob',
            name='source',
        ),
        migrations.AddField(
            model_name='datacollectionjob',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='수집 소스의 모델 타입 (NewsSource 또는 SocialMediaSource)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='소스 타입'),
        ),
        migrations.AddField(
            model_name='datacollectionjob',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='수집 소스의 ID', null=True, verbose_name='소스 ID'),
        ),
    ]
