# Generated by Django 4.2.7 on 2025-12-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0008_remove_datacollectionjob_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='original_content',
            field=models.TextField(blank=True, help_text='번역 전 원본 내용 (content가 번역된 경우 저장)', null=True, verbose_name='원본 내용'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='original_title',
            field=models.CharField(blank=True, help_text='번역 전 원본 제목 (title이 번역된 경우 저장)', max_length=500, null=True, verbose_name='원본 제목'),
        ),
    ]
