# Generated by Django 4.2.7 on 2025-12-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0009_socialmediapost_original_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='score',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='upvotes',
        ),
    ]
