# Generated by Django 4.2.7 on 2026-01-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0010_remove_socialmediapost_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='뉴스 기사의 썸네일 이미지 URL', max_length=1000, null=True, verbose_name='썸네일 이미지 URL'),
        ),
    ]
