# Generated by Django 4.2.28 on 2026-03-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collector", "0011_newsarticle_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.URLField(
                db_index=True,
                help_text="뉴스 기사의 원본 URL (중복 방지용)",
                max_length=2000,
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
