# Generated by Django 4.2.7 on 2026-01-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("answer_text", models.TextField()),
                ("sources", models.JSONField(blank=True, default=list)),
                ("top_k", models.PositiveIntegerField(default=5)),
                (
                    "collection",
                    models.CharField(default="trend_docs", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
