# Generated by Django 4.2.28 on 2026-02-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_update_full_collect_analyze_to_1hour"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trendanalysisresult",
            new_name="analyzer_tr_analysi_60a193_idx",
            old_name="analyzer_tr_analysis_6e76f2_idx",
        ),
        migrations.RenameIndex(
            model_name="trendanalysisresult",
            new_name="analyzer_tr_analysi_1d0216_idx",
            old_name="analyzer_tr_analysis_7c4a44_idx",
        ),
    ]
