# Generated by Django 4.2.28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_rename_analyzer_tr_analysis_6e76f2_idx_analyzer_tr_analysi_60a193_idx_and_more"),
        ("analyzer", "0004_rename_analyzer_tr_analysis_6e76f2_idx_analyzer_tr_analysi_60a193_idx_and_more"),
    ]

    operations = []
